// <auto-generated />
using System;
using CiCd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CiCd.Migrations
{
    [DbContext(typeof(CiCdDbContext))]
    partial class CiCdDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CiCd.Models.Artifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RunLogId")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RunLogId");

                    b.ToTable("Artifacts");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            BlobUrl = "https://s3.example.com/artifacts/api.zip",
                            CreatedAt = new DateTime(2024, 5, 1, 10, 8, 0, 0, DateTimeKind.Utc),
                            FileName = "api.zip",
                            RunLogId = 1,
                            SizeBytes = 512000L
                        },
                        new
                        {
                            Id = 11,
                            BlobUrl = "https://s3.example.com/artifacts/dist.zip",
                            CreatedAt = new DateTime(2024, 5, 3, 14, 5, 0, 0, DateTimeKind.Utc),
                            FileName = "dist.zip",
                            RunLogId = 3,
                            SizeBytes = 204800L
                        });
                });

            modelBuilder.Entity("CiCd.Models.Pipeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Pipelines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Branch = "main",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build and test on every push",
                            IsEnabled = true,
                            Name = "CI Pipeline",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Branch = "main",
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lint and build the frontend bundle",
                            IsEnabled = true,
                            Name = "Frontend CI",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            Branch = "main",
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Validate, plan and apply infrastructure changes",
                            IsEnabled = false,
                            Name = "Terraform Apply",
                            ProjectId = 3
                        });
                });

            modelBuilder.Entity("CiCd.Models.PipelineStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ContinueOnError")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("PipelineId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId");

                    b.ToTable("PipelineSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Command = "dotnet build",
                            ContinueOnError = false,
                            Name = "Build",
                            Order = 1,
                            PipelineId = 1,
                            TimeoutSeconds = 120
                        },
                        new
                        {
                            Id = 2,
                            Command = "dotnet test",
                            ContinueOnError = false,
                            Name = "Test",
                            Order = 2,
                            PipelineId = 1,
                            TimeoutSeconds = 180
                        },
                        new
                        {
                            Id = 3,
                            Command = "./deploy.sh",
                            ContinueOnError = false,
                            Name = "Deploy",
                            Order = 3,
                            PipelineId = 1,
                            TimeoutSeconds = 60
                        },
                        new
                        {
                            Id = 4,
                            Command = "npm run lint",
                            ContinueOnError = false,
                            Name = "Lint",
                            Order = 1,
                            PipelineId = 2,
                            TimeoutSeconds = 60
                        },
                        new
                        {
                            Id = 5,
                            Command = "npm run build",
                            ContinueOnError = false,
                            Name = "Build",
                            Order = 2,
                            PipelineId = 2,
                            TimeoutSeconds = 120
                        },
                        new
                        {
                            Id = 6,
                            Command = "terraform validate",
                            ContinueOnError = false,
                            Name = "Validate",
                            Order = 1,
                            PipelineId = 3,
                            TimeoutSeconds = 30
                        },
                        new
                        {
                            Id = 7,
                            Command = "terraform plan",
                            ContinueOnError = false,
                            Name = "Plan",
                            Order = 2,
                            PipelineId = 3,
                            TimeoutSeconds = 120
                        },
                        new
                        {
                            Id = 8,
                            Command = "terraform apply",
                            ContinueOnError = false,
                            Name = "Apply",
                            Order = 3,
                            PipelineId = 3,
                            TimeoutSeconds = 300
                        });
                });

            modelBuilder.Entity("CiCd.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Backend REST API service",
                            IsActive = true,
                            Name = "REST API",
                            OwnerId = 1,
                            RepositoryUrl = "https://github.com/example/rest-api"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "React/TypeScript frontend application",
                            IsActive = true,
                            Name = "Frontend",
                            OwnerId = 3,
                            RepositoryUrl = "https://github.com/example/frontend"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Terraform configs and deployment scripts",
                            IsActive = false,
                            Name = "Infrastructure",
                            OwnerId = 1,
                            RepositoryUrl = "https://github.com/example/infra"
                        });
                });

            modelBuilder.Entity("CiCd.Models.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JoinedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 1,
                            Role = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            JoinedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 1,
                            Role = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            JoinedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 1,
                            Role = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            JoinedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 2,
                            Role = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            JoinedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 2,
                            Role = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            JoinedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 3,
                            Role = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            JoinedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 3,
                            Role = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            JoinedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 3,
                            Role = 2,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("CiCd.Models.RunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogOutput")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<int>("PipelineId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerType")
                        .HasColumnType("integer");

                    b.Property<int>("TriggeredByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId");

                    b.HasIndex("TriggeredByUserId");

                    b.ToTable("RunLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinishedAt = new DateTime(2024, 5, 1, 10, 8, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Pipeline started.",
                            PipelineId = 1,
                            StartedAt = new DateTime(2024, 5, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            TriggerType = 1,
                            TriggeredByUserId = 2
                        },
                        new
                        {
                            Id = 2,
                            FinishedAt = new DateTime(2024, 5, 2, 9, 3, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Pipeline started.",
                            PipelineId = 1,
                            StartedAt = new DateTime(2024, 5, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3,
                            TriggerType = 3,
                            TriggeredByUserId = 1
                        },
                        new
                        {
                            Id = 3,
                            FinishedAt = new DateTime(2024, 5, 3, 14, 5, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Pipeline started.",
                            PipelineId = 2,
                            StartedAt = new DateTime(2024, 5, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            TriggerType = 1,
                            TriggeredByUserId = 3
                        },
                        new
                        {
                            Id = 4,
                            LogOutput = "Pipeline started.",
                            PipelineId = 2,
                            StartedAt = new DateTime(2024, 5, 4, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TriggerType = 0,
                            TriggeredByUserId = 2
                        },
                        new
                        {
                            Id = 5,
                            FinishedAt = new DateTime(2024, 4, 10, 8, 7, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Pipeline started.",
                            PipelineId = 3,
                            StartedAt = new DateTime(2024, 4, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            TriggerType = 0,
                            TriggeredByUserId = 1
                        },
                        new
                        {
                            Id = 6,
                            FinishedAt = new DateTime(2024, 4, 15, 12, 2, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Pipeline started.",
                            PipelineId = 3,
                            StartedAt = new DateTime(2024, 4, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = 4,
                            TriggerType = 2,
                            TriggeredByUserId = 1
                        });
                });

            modelBuilder.Entity("CiCd.Models.StepRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogOutput")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<int>("RunLogId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StepId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RunLogId");

                    b.HasIndex("StepId");

                    b.ToTable("StepRuns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExecutionOrder = 1,
                            ExitCode = 0,
                            FinishedAt = new DateTime(2024, 5, 1, 10, 3, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Build started...\nRestore completed.\nBuild succeeded.",
                            RunLogId = 1,
                            StartedAt = new DateTime(2024, 5, 1, 10, 0, 1, 0, DateTimeKind.Utc),
                            Status = 2,
                            StepId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExecutionOrder = 2,
                            ExitCode = 0,
                            FinishedAt = new DateTime(2024, 5, 1, 10, 7, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Test run started...\n42 tests passed.\n0 failed.",
                            RunLogId = 1,
                            StartedAt = new DateTime(2024, 5, 1, 10, 3, 1, 0, DateTimeKind.Utc),
                            Status = 2,
                            StepId = 2
                        },
                        new
                        {
                            Id = 3,
                            ExecutionOrder = 3,
                            ExitCode = 0,
                            FinishedAt = new DateTime(2024, 5, 1, 10, 8, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Deploying...\nDeployment complete.",
                            RunLogId = 1,
                            StartedAt = new DateTime(2024, 5, 1, 10, 7, 1, 0, DateTimeKind.Utc),
                            Status = 2,
                            StepId = 3
                        },
                        new
                        {
                            Id = 4,
                            ExecutionOrder = 1,
                            ExitCode = 0,
                            FinishedAt = new DateTime(2024, 5, 2, 9, 2, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Build started...\nBuild succeeded.",
                            RunLogId = 2,
                            StartedAt = new DateTime(2024, 5, 2, 9, 0, 1, 0, DateTimeKind.Utc),
                            Status = 2,
                            StepId = 1
                        },
                        new
                        {
                            Id = 5,
                            ErrorMessage = "Test project failed: assertion in PaymentServiceTests.ShouldChargeAmount.",
                            ExecutionOrder = 2,
                            ExitCode = 1,
                            FinishedAt = new DateTime(2024, 5, 2, 9, 3, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Test run started...\n3 tests failed.",
                            RunLogId = 2,
                            StartedAt = new DateTime(2024, 5, 2, 9, 2, 1, 0, DateTimeKind.Utc),
                            Status = 3,
                            StepId = 2
                        },
                        new
                        {
                            Id = 6,
                            ExecutionOrder = 1,
                            ExitCode = 0,
                            FinishedAt = new DateTime(2024, 5, 3, 14, 2, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Lint started...\nNo lint errors.",
                            RunLogId = 3,
                            StartedAt = new DateTime(2024, 5, 3, 14, 0, 1, 0, DateTimeKind.Utc),
                            Status = 2,
                            StepId = 4
                        },
                        new
                        {
                            Id = 7,
                            ExecutionOrder = 2,
                            ExitCode = 0,
                            FinishedAt = new DateTime(2024, 5, 3, 14, 5, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Build started...\nBundle created.",
                            RunLogId = 3,
                            StartedAt = new DateTime(2024, 5, 3, 14, 2, 1, 0, DateTimeKind.Utc),
                            Status = 2,
                            StepId = 5
                        },
                        new
                        {
                            Id = 8,
                            ExecutionOrder = 1,
                            LogOutput = "Lint started...",
                            RunLogId = 4,
                            StartedAt = new DateTime(2024, 5, 4, 9, 30, 1, 0, DateTimeKind.Utc),
                            Status = 1,
                            StepId = 4
                        },
                        new
                        {
                            Id = 9,
                            ExecutionOrder = 1,
                            ExitCode = 0,
                            FinishedAt = new DateTime(2024, 4, 10, 8, 1, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Terraform validate passed.",
                            RunLogId = 5,
                            StartedAt = new DateTime(2024, 4, 10, 8, 0, 1, 0, DateTimeKind.Utc),
                            Status = 2,
                            StepId = 6
                        },
                        new
                        {
                            Id = 10,
                            ExecutionOrder = 2,
                            ExitCode = 0,
                            FinishedAt = new DateTime(2024, 4, 10, 8, 4, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Plan: 2 to add, 0 to change, 0 to destroy.",
                            RunLogId = 5,
                            StartedAt = new DateTime(2024, 4, 10, 8, 1, 1, 0, DateTimeKind.Utc),
                            Status = 2,
                            StepId = 7
                        },
                        new
                        {
                            Id = 11,
                            ExecutionOrder = 3,
                            ExitCode = 0,
                            FinishedAt = new DateTime(2024, 4, 10, 8, 7, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Apply complete. Resources created.",
                            RunLogId = 5,
                            StartedAt = new DateTime(2024, 4, 10, 8, 4, 1, 0, DateTimeKind.Utc),
                            Status = 2,
                            StepId = 8
                        },
                        new
                        {
                            Id = 12,
                            ExecutionOrder = 1,
                            ExitCode = 0,
                            FinishedAt = new DateTime(2024, 4, 15, 12, 1, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Terraform validate passed.",
                            RunLogId = 6,
                            StartedAt = new DateTime(2024, 4, 15, 12, 0, 1, 0, DateTimeKind.Utc),
                            Status = 2,
                            StepId = 6
                        },
                        new
                        {
                            Id = 13,
                            ExecutionOrder = 2,
                            FinishedAt = new DateTime(2024, 4, 15, 12, 2, 0, 0, DateTimeKind.Utc),
                            LogOutput = "Plan in progress...\nRun cancelled by user.",
                            RunLogId = 6,
                            StartedAt = new DateTime(2024, 4, 15, 12, 1, 1, 0, DateTimeKind.Utc),
                            Status = 4,
                            StepId = 7
                        });
                });

            modelBuilder.Entity("CiCd.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "root@example.com",
                            PasswordHash = "$2a$12$ybfAz8xjizHsbJIkLP4M/.t9c2qXPIoQ9buTjC.Y4LPS4ZH1txBoW",
                            Role = 0,
                            Username = "root"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@example.com",
                            PasswordHash = "$2a$12$ybfAz8xjizHsbJIkLP4M/.t9c2qXPIoQ9buTjC.Y4LPS4ZH1txBoW",
                            Role = 1,
                            Username = "bob"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol@example.com",
                            PasswordHash = "$2a$12$ybfAz8xjizHsbJIkLP4M/.t9c2qXPIoQ9buTjC.Y4LPS4ZH1txBoW",
                            Role = 1,
                            Username = "carol"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dave@example.com",
                            PasswordHash = "$2a$12$ybfAz8xjizHsbJIkLP4M/.t9c2qXPIoQ9buTjC.Y4LPS4ZH1txBoW",
                            Role = 2,
                            Username = "dave"
                        });
                });

            modelBuilder.Entity("CiCd.Models.Artifact", b =>
                {
                    b.HasOne("CiCd.Models.RunLog", "RunLog")
                        .WithMany("Artifacts")
                        .HasForeignKey("RunLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunLog");
                });

            modelBuilder.Entity("CiCd.Models.Pipeline", b =>
                {
                    b.HasOne("CiCd.Models.Project", "Project")
                        .WithMany("Pipelines")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CiCd.Models.PipelineStep", b =>
                {
                    b.HasOne("CiCd.Models.Pipeline", "Pipeline")
                        .WithMany("Steps")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("CiCd.Models.Project", b =>
                {
                    b.HasOne("CiCd.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CiCd.Models.ProjectMember", b =>
                {
                    b.HasOne("CiCd.Models.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CiCd.Models.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CiCd.Models.RunLog", b =>
                {
                    b.HasOne("CiCd.Models.Pipeline", "Pipeline")
                        .WithMany("RunLogs")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CiCd.Models.User", "TriggeredBy")
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pipeline");

                    b.Navigation("TriggeredBy");
                });

            modelBuilder.Entity("CiCd.Models.StepRun", b =>
                {
                    b.HasOne("CiCd.Models.RunLog", "RunLog")
                        .WithMany("StepRuns")
                        .HasForeignKey("RunLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CiCd.Models.PipelineStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunLog");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("CiCd.Models.Pipeline", b =>
                {
                    b.Navigation("RunLogs");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CiCd.Models.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Pipelines");
                });

            modelBuilder.Entity("CiCd.Models.RunLog", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("StepRuns");
                });

            modelBuilder.Entity("CiCd.Models.User", b =>
                {
                    b.Navigation("ProjectMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
